spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    #配置eureka服务器地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


